### ISSUE TITLE
Should the tokenization task force standardize an interface   between payment apps and tokenization service providers?

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-methods-tokenization#14]
This [wiki entry](https://github.com/w3c/webpayments-methods-tokenization/wiki/gateway_params) has a lot of detail about the interface between the Payment App and the Token Service Provider.

Are we intending to standardise that interface, or is that outside of scope of w3c?

My concerns with standardising are;

1. The Payments WG has not to date looked at this type of interface
2. This is outside the scope of what a PMI is, which documents the data exchanged between the merchant and user-agent via the PaymentRequest API

Even if we were to take this on, I propose that this is left until we have developed the PMI part and standardise the interface between merchant and user-agent. This will allow us to focus on one piece at a time.

**Comment by MasterKeyur** [comment]
I think that should not be charter of W3C but EMVCo has already made huge progress by publishing it. But they are always variation due to specification allowing for customization.

**Comment by ianbjacobs** [comment]
I am closing this issue both because the current proposal [1] no longer posits an interface between app and TSP and also because I think issue #25 [2] may touch on the same topic from another perspective.

We can reopen if needed.

Ian

[1] https://github.com/w3c/webpayments-methods-tokenization/wiki/Tokenized-Card
[2] https://github.com/w3c/webpayments-methods-tokenization/issues/25
