### ISSUE TITLE
Inconsistencies in response example

### ISSUE THREAD

**Issue by stpeter** [w3c/webpayments-methods-tokenization#37]
In the response example, there are data inconsistencies:

displayLast4: "***6789" vs. cardNumber: "5413339000001513"
displayExpiryMonth: "02" vs. expiryMonth: "12"
displayExpiryYear: "22" vs. expiryYear: "20"

Are these intentional?

**Comment by ianbjacobs** [comment]
Yes, that's intentional. (Whether it is correct is still a valid question.)

My understanding is that the tokenization process creates this dynamic data, which is different from the "real" static data of the card. That's why the display dates are different from dynamically generated dates, and the "last4" is the REAL last 4, as opposed to the dynamic PAN that results from tokenization.

Ian

**Comment by stpeter** [comment]
Makes sense, just wanted to be sure.

**Comment by ianbjacobs** [comment]
I'm going to close this for now. Thanks, @stpeter
