### ISSUE TITLE
Opportunities 

### ISSUE THREAD

**Issue by MasterKeyur** [w3c/webpayments-methods-tokenization#6]
I would recommend following putting out clear indications toward future --

- Pass tokens that are authorized by user and generated in the payment app to the merchant (or PSP) so merchants does not need to be PCI-DSS compliant

- With higher authentication linked to device and user (biometric), certain type of tokens would bring in liability shift to merchants for the transaction

- Standard way of passing token from payment app to merchant such that PSP integrated with merchant can process payment with that token.

**Comment by ianbjacobs** [comment]
Hi @MasterKeyur,

I've made edits to incorporate your suggestions. Please let me know if you are satisfied with this text.

Ian

   * Pass tokens generated through payment apps (e.g., by vault services) and authorized by users to the merchant (or PSP) to eliminate PCI-DSS compliance issues (by eliminating merchant exposure to PANs).
   * Enable liability shifts by making it easier to circulate tokens that result from strong authentication (e.g., mobile device-enabled biometrics).
   *  Harmonize how tokens are communicated to the merchant (through the Payment Request API) so that it is easier for PSPs integrated with the merchant to use the token to process a payment.

**Comment by MasterKeyur** [comment]
Thanks Ian. It is looking good.


Keyur Patel
Consultant, Software Engineering
Design Team | DST

MasterCard
114 fifth Avenue| NYC, NY 10014
 Mobile 1-9144139421
keyur.patel@mastercard.com
[cid:image001.png@01D2CE34.FED3CB80]<www.mastercard.com>

**Comment by ianbjacobs** [comment]
Closing since reviewer satisfied.
