### ISSUE TITLE
Gateway params sequence

### ISSUE THREAD

**Issue by MasterKeyur** [w3c/webpayments-methods-tokenization#8]
In the diagram it seems nonce is shared by the GW when card is tokenized. Please can you check if the GW can provide the token itself and tokenized card id. So merchant does not have to make backend call to retrieve token from PSP but just request PSP to process payment on given token. This is more similar to current existing merchant integration according to my understanding. 

On subsequent checkout (existing diagram), are we sending the tokenized card id or nonce? Once we know the answer then we can decide if browser can share the token itself.

**Comment by oyiptong** [comment]
> On subsequent checkout (existing diagram), are we sending the tokenized card id or nonce? Once we know the answer then we can decide if browser can share the token itself.

On subsequent checkout, only the card id is sent

The `nonce` is a one-time use identifier. it is discarded after the initial emission to the merchant.
The reason for sending the `nonce` instead of the `token`, then `id` subsequently is to increase security.

## Token passing
Let's consider passing the `token` to the user agent.

One of the uses of the `token` is for repeated offline use. If we send the `token` to the user agent, we're trusting that the user's machine is not compromised, because that `token`, when put in the wrong hands, are one of the keys required for an attacker to usurp the merchant.

An attacker would need to identify itself to a gateway, then provide the `token` to initiate transactions.

Requirements for fraudulent transaction:
1. merchant credentials on gateway
2. token

## Nonce passing

Let's now consider the use of a one-time token, a.k.a. the `nonce`.

The `nonce` is discarded by the user agent right after sending it to the merchant.

The upside of using the `nonce` is that any program (malicious addons, rootkits and other spyware) watching the user agent's databases and memory will only find useless fragments of data. It won't be useful at all to any attackers.

Passing the `id` is much safer. That means that an attacker would also need to break into the merchant's infrastructure to obtain the `id` and `token` mappings.

Requirements for fraudulent transaction:
1. merchant credentials on gateway
2. id
3. token (breaking into merchant infra to obtain it)

**Comment by MasterKeyur** [comment]
I think it depends on how strong the merchant credential is to communicate to GW. Usually here we are  looking at network security (VPN, TLS etc) plus some additional data security (encryption or signature).  Either one of them is strong enough. I think even if token goes to wrong hand he would not be able to identify the PSP and have merchant credentials. This can be discussed with existing merchants who are integrated to GW. 

My point was on subsequent transaction you were still passing id stored in browser. so you are still having static value in browser which is sent to merchant. Then relying on merchant to get token. So here you are relying on merchant credentials. if they get compromised then hacker can use static id to get token. 

I think we are creating extra security here which would not useful and make the transaction take longer to process. Also I think of GW as payment processor so basically merchant would request the GW to process the payment of X amount and they would need merchant info for that. 

We can simplify this further I think and improve user experience without compromising on security. we can have a call to discuss further.

**Comment by oyiptong** [comment]
> I think it depends on how strong the merchant credential is to communicate to GW. Usually here we are looking at network security (VPN, TLS etc)

Are you saying that you require mTLS (or VPN) for the merchant to gateway/psp communication?

> My point was on subsequent transaction you were still passing id stored in browser. so you are still having static value in browser which is sent to merchant. Then relying on merchant to get token. So here you are relying on merchant credentials. if they get compromised then hacker can use static id to get token.

Yes that's what I imply. Breaking into the merchant infrastructure should be harder than breaking into the end-user's computer.

> We can simplify this further I think and improve user experience without compromising on security. we can have a call to discuss further.

Sounds good. Let's have a chat

**Comment by ianbjacobs** [comment]
I propose that the gateway tokenization folks meet again. I will start a scheduling thread.
Ian

**Comment by ianbjacobs** [comment]
Closed with @MasterKeyur's support after edits to https://github.com/w3c/webpayments-methods-tokenization/wiki/gateway_params

See 20 June 2017 minutes
https://www.w3.org/2017/06/20-wpwg-minutes.html#item03

Ian
